issuers:
  ministry-finance:
    logo_path: ''
    name: BC Ministry of Finance
    abbreviation: Ministry of Finance
    email: minfinance.test.issuer@example.ca
    url: $APPLICATION_URL_INCORP

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-mofi_issuer}
      seed: $INDY_WALLET_SEED
      type: $INDY_WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
      - description: PST Number
        schema: pst_number.permitify
        issuer_url: $APPLICATION_URL_INCORP
        topic:
          source_id:
            input: corp_num
            from: claim
          type:
            input: registration
            from: value

verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  registration:
    version: '1.0.4'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: registration.permitify
          version: '1.0.4'
        attributes:
          - corp_num
          # - address_line_1
          # - address_line_2
          # - addressee
          # - city
          # - country
          - legal_name
          # - postal_code
          # - province
